[package]
name = "ocaml-sexplib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
bstr = "1"
insta = "1.43"
serde_bytes = "0.11"
